upload_max_filesize = 10M
post_max_size = 12M
max_execution_time = 60
memory_limit = 256M
session.cookie_path = /
session.gc_maxlifetime = 7200
session.cookie_lifetime = 0
session.cookie_httponly = 1
session.cookie_samesite = Lax
session.use_strict_mode = 1
