#!/bin/bash
# Supabase Setup Guide for Smart Learning Backend

echo "═══════════════════════════════════════════════════════════"
echo "Supabase Database Setup for Smart Learning"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEP 1: Load Schema into Supabase"
echo "─────────────────────────────────────────────────────────"
echo "1. Go to https://supabase.com/projects"
echo "2. Select your project"
echo "3. Go to SQL Editor (left sidebar)"
echo "4. Click 'New Query'"
echo "5. Copy-paste ALL content from: backend/sql/schema.sql"
echo "6. Click 'Run'"
echo ""
echo "STEP 2: Load Seed Data (Optional)"
echo "─────────────────────────────────────────────────────────"
echo "1. In SQL Editor, click 'New Query' again"
echo "2. Copy-paste ALL content from: backend/sql/seed.sql"
echo "3. Click 'Run'"
echo ""
echo "STEP 3: Verify Connection"
echo "─────────────────────────────────────────────────────────"
echo "1. Open terminal and navigate to: cd takizip/taki"
echo "2. Start PHP server: php -S localhost:8000"
echo "3. Open browser: http://localhost:8000/health.php"
echo "4. You should see a SUCCESS message with DB info"
echo ""
echo "STEP 4: Test the App"
echo "─────────────────────────────────────────────────────────"
echo "1. Go to: http://localhost:8000"
echo "2. Create an account (register)"
echo "3. Login with your credentials"
echo "4. Check Supabase Table Editor - new user should appear in 'users' table"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Environment variables are already set in: .env"
echo "═══════════════════════════════════════════════════════════"
